### PR TITLE
Use codepoints instead of char.

### LINKED ISSUE #167: Define 'Character' with respect to password validation
The `LengthRule` uses `String.length()` in order to determine the number of characters in a password. This leads to unexpected results when using Unicode Characters. This implementation ties the length of a password to the specification of `java.lang.Character` and primitive `char` types.

| Character/Symbol | Number of `Character` (`String.length()`) | Number of bytes |
|--------|--------|--------|
| `a` | 1 | 1 |
| `Ä` | 1 | 2 |
| `€` | 1 | 3 |
| 🌲 | 2 | 4 |
| 🇻🇺 | 4 | 8 |

Given our password policy that enforces - among other things - a minimum length of 10 characters the password "Ab1!🇻🇺🌲" is considered valid although from a visual perspective it does consist of 6 "symbols", only.

Password hashing algorithms like BCrypt are limited to 72 bytes and some implementations will [truncate passwords to those 72 bytes](https://en.wikipedia.org/wiki/Bcrypt#:~:text=Many%20implementations%20of%20bcrypt%20truncate,to%2072%20octets%2Fbytes).). Additional symbols wouldn't be recognized. Additionally the 72 byte limit will be [enforced by Spring Security since yesterday](https://spring.io/security/cve-2025-22228).

This leads me to the following observations:
- A good password policy should limit the length of the password when using BCrypt algorithm to hash those passwords and avoid a false sense of security for the user when his passwords will be eventually truncated.
- The current implementation of `LengthRule` is tied to `java.lang.Character` specification where one `Character` is at most 3 bytes long. Thus using an upper limit of 24 will ensure the technical restrictions of BCrypt will be met.
- When configured with an (upper) limit `LengthRule` behaviour is unexpected from an end-user perspective.

For example when limiting the length to 12 characters
-  "A🇻🇺🇻🇺🇻🇺" is an invalid (too long) password
- "Wag0nmast€r🌲" is an invalid (too long) password either

I'd guess that "regular users" won't use flags and trees in their passwords. But testers do ;-).

What's your take on the "Character" definition? Should there be a `BinaryLengthRule` as well? I thought about implementing one myself but struggeled with a good error message I could present to users (when using Euro sign/ currency symbols in their passwords and exceeding the binary limit).

### PR DESCRIPTION
**Pull request by dfish3r**
Update the API to use int instead of char.
Bump version to v2.0.0-SNAPSHOT, many API breaking changes. Fixes #167.

### CODE REVIEW

File: src/main/java/org/passay/AllowedCharacterRule.java [hunk 1]
```diff
@@ -40,6 +41,17 @@ public AllowedCharacterRule(final char[] c)
   }
 
 
+  /**
+   * Create a new allowed character rule.
+   *
+   * @param  cp  allowed character code points
+   */
+  public AllowedCharacterRule(final int[] cp)
```
Comment (serac) [inline src/main/java/org/passay/AllowedCharacterRule.java:49]: The use of int is jarring here. Given the central concern of rule construction as a means to implementing password policy, I'd like to see a `CodePoint` type that facilitates conversion of strings and characters to the types needed by this API:

    new AllowedCharacterRule(new CodePoint("abcdefghikjlmnopqrstuvwxyz"));

You have `PaswordUtils` performing these conversions now, but I'd like to see all the string-to-code-point conversion concerns moved to this type.

File: src/main/java/org/passay/AllowedCharacterRule.java [hunk 2]
```diff
@@ -73,8 +109,21 @@ public AllowedCharacterRule(final char[] c, final boolean reportAll)
    */
   public AllowedCharacterRule(final char[] c, final MatchBehavior behavior, final boolean reportAll)
```
Comment (serac) [inline src/main/java/org/passay/AllowedCharacterRule.java:110]: Recommend to go all the way and remove characters/strings from all public APIs. You're making a thoughtful change for the sake of internationalization by switching to UTF-8, and you're liable to invite the kinds of problems you want to solve by coercing to characters _before_ converting to code points. If nothing else I feel it invites confusion about the implementation using UTF-8 internally. With a dedicated type, `CodePoint` for this concern, which should have helpful constructors/converters, there's no need to provide these overloaded methods.

File: src/test/java/org/passay/AllowedCharacterRuleTest.java [hunk 3]
```diff
@@ -75,6 +75,33 @@ public Object[][] passwords()
           new PasswordData("gbwersco4kk"),
           null,
         },
+        // test unicode
+        {
+          new AllowedCharacterRule(ALLOWED_CHARS),
```
Comment (serac) [inline src/test/java/org/passay/AllowedCharacterRuleTest.java:80]: I had hoped to see some test coverage indicating how to create rules using code points. That's the heart of the change, and seeing at least one test that demonstrates it seems warranted.

**Review by serac — APPROVED** [review]
I think this is a bold change, but one that clearly moves toward improved internationalization support and in particular support for Asian languages that require 3 or more bytes in the encoding. My only real material concern is the use of `int[]` to describe code points. While the JDK uses this type, presumably for performance, a dedicated type is warranted for usability and clarity of the API contract. I should also note that you're practically forcing users to have a working knowledge of UTF-8 concepts in order to use the API. While I think that's a reasonable and even beneficial requirement in 2025, it is a notable one and comes at a non-trivial cost.

File: src/main/java/org/passay/AllowedCharacterRule.java (hunk 1 above)
Comment (dfish3r) [reply src/main/java/org/passay/AllowedCharacterRule.java]: Fixed, added `CodePoints` class.

File: src/main/java/org/passay/AllowedCharacterRule.java (hunk 2 above)
Comment (serac) [reply src/main/java/org/passay/AllowedCharacterRule.java]: After reviewing your new class I had some insight on a better name that I proposed with a PR: https://github.com/vt-middleware/passay/pull/173
